### ISSUE TITLE
config param cause the client seems block

### ISSUE THREAD

**Issue by smallmenu** [brianlmoon/GearmanManager#101]
I want to use gearmanmanager to manage some workers, but,
in the config file , i do not  understand some param, such as count, dedicated_count,dedicated_only or count in the subsection
for example:
i have two workers,Default and Test,my config file is:
[GearmanManager]
worker_dir=/data/www/Service/Gearman
auto_update=1
count=3
max_worker_lifetime=3600
timeout=300
dedicated_count=1
[Default]
dedicated_count=5
dedicated_only=1
[Test]
count=3
restart gearmand,gearmanmanager
when if run a client script for test, it seems block all the time. 
the client sciprt is simple, use doBackground() method
even so, the gearmand_status.php seems block too.

then i modify the config like this :
[GearmanManager]
worker_dir=/data/www/Service/Gearman/
auto_update=1
count=5
restart gearmand, gearmanmanager,

it works fine.

I do not know the reason , can you give me some suggestion?

my enviroment is :
centos 6.4 x86_64
php 5.4.25
pecl gearman 1.1.2

**Comment by brianlmoon** [comment]
This sounds like a problem in the PECL lib. We simply pass that value to the PECL lib and it does what it does with it.
