### ISSUE TITLE
Child Process Exiting Unexpectedly

### ISSUE THREAD

**Issue by gorlinj** [brianlmoon/GearmanManager#107]
Hi All,

I have written a few workers to do routine functions like sending email. Very rarely (although reproducible) I am getting processes that are exiting such as:

```
PROC   Child 57871 exited (send_email)
```

I have tried to turn on the logging and it looks like it is failing before my worker function is called. How can I debug this further? I have added Xdebug and turned on scream but I'm not sure where to look now?

Any help would be greatly appreciated.

Thanks.

**Comment by brianlmoon** [comment]
You should use include_once() and outside of the function.
