### ISSUE TITLE
getopt empty

### ISSUE THREAD

**Issue by NanoCaiordo** [brianlmoon/GearmanManager#113]
Hello, I've recently installed GearmanManager on a CloudLinux Server release 6.6 X-Powered-By PHP/5.4.39 and it wasn't able to find the ./workers dir. I soon realized that none of the parameters was passed to the script.

/etc/rc.d/init.d/gearman-manager correctly try to daemonize the script with
`deamon --pidfile=/var/run/gearman/manager.pid /usr/local/bin/gearman-manager -P /var/run/gearman/manager.pid -l /var/log/gearman-manager.log -u gearmand -d -c /etc/gearman-manager/config.ini`

In /usr/local/share/gearman-manager/pecl-manager.php I've then placed `exit(var_dump(getopt("ac:dD:h:Hl:o:p:P:u:v::w:r:x:Z")));`  and its output is:
 ```
bool(false)
```

However `exit(var_dump($argv));` outputs:
```
array(10) {
  [0] => string(30) "/usr/local/bin/gearman-manager"
  [1] => string(2) "-P"
  [2] => string(28) "/var/run/gearman/manager.pid"
  [3] => string(2) "-l"
  [4] => string(28) "/var/log/gearman-manager.log"
  [5] => string(2) "-u"
  [6] => string(8) "gearmand"
  [7] => string(2) "-d"
  [8] => string(2) "-c"
  [9] => string(31) "/etc/gearman-manager/config.ini"
}
```

**Comment by brianlmoon** [comment]
Hmm, I don't know why that would return false. The PHP docs say it returns false on failure, but does not really say why getopt would fail. http://php.net/getopt#refsect1-function.getopt-returnvalues

Can you try adding error_reporting(-1) to the file to show what PHP errors may be ocurring?

**Comment by NanoCaiordo** [comment]
```
error_reporting(-1);
ini_set('error_log', '/var/log/gearman-manager.log');
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
```

`cat /var/log/gearman-manager.log` is still empty (thus I did make sure that error_log('test') successfully wrote to gearman-manager.log which it did).

**Comment by conradjones** [comment]
IIRC you need to set -v or -vv or -vvv in the params line in the init.d
script

e.g.  my init.d script for one of my workers contains this line.

PARAMS="-c ${CONFIGDIR}/config.ini -vvv"

**Comment by NanoCaiordo** [comment]
Same problem, -vvv doesn't enable any verbose debugging.

**Comment by conradjones** [comment]
The options go all the way up to -vvvvv try that first and then work
backwards.

**Comment by NanoCaiordo** [comment]
Nothing to do, but if I execute
`/usr/local/bin/gearman-manager -P /var/run/gearman/manager.pid -l /var/log/gearman-manager.log -u root -d -c /etc/gearman-manager/config.ini` then gotopt() is properly filled. It is clear to me that `daemon` doesn't let pass any parameter and logs are empty from relevant data.

**Comment by NanoCaiordo** [comment]
Gearman-manager is not the issue, I've created a start up script and a php file and the problem persist.
I'm closing this issue and opened one at php.net https://bugs.php.net/bug.php?id=69421

Cheers

**Comment by conradjones** [comment]
Can you not upgrade your version of PHP? I'm running 5.6.7-1 here.

**Comment by NanoCaiordo** [comment]
Upgrading to 5.5 was enough to fix it. Thank you.
