### ISSUE TITLE
The count param in config.ini is not works

### ISSUE THREAD

**Issue by gzldx** [brianlmoon/GearmanManager#115]
[GearmanManager]
; workers can be found in this dir
worker_dir= XXXXXXXXX

; Reload workers as new code is available
auto_update=1
count=10
[GearmanManager]
; workers can be found in this dir
worker_dir=/data/www/weili/trunk/worker

; Reload workers as new code is available
auto_update=1
dedicated_count=1
count=10

I have set 10 worker to do the job，but why is only 1 worker start？
![qq 20150512185235](https://cloud.githubusercontent.com/assets/2508193/7585764/676ba7aa-f8d8-11e4-82ca-478627d0dfe5.png)

**Comment by brianlmoon** [comment]
I see 3 and you don't even show the whole ps output. Gearmand is the process server.

**Comment by gzldx** [comment]
How can I see the worker process id? I config count = 10 in config.ini, but I just see 1 worker process in  gearman monitor

**Comment by brianlmoon** [comment]
I am not familiar with gearman monitor. Can you show me the full ps output?

**Comment by gzldx** [comment]
$ sudo /etc/init.d/gearman-manager start
* Starting Gearman Manager

$ sudo /data/git/GearmanManager/pecl-manager.php -c /etc/gearman-manager/config.ini -d

$ cat /etc/gearman-manager/config.ini 
[GearmanManager]
; workers can be found in this dir
worker_dir=/data/www/weili/trunk/worker

; Reload workers as new code is available
auto_update=1
;dedicated_count=2
count=10

But I just found 2 workers have been started..
![qq 20150513135839](https://cloud.githubusercontent.com/assets/2508193/7604653/318d2ece-f978-11e4-88ef-1cbfe3012b60.png)

**Comment by gzldx** [comment]
![qq 20150513141107](https://cloud.githubusercontent.com/assets/2508193/7604748/fc4473b0-f979-11e4-986e-d6e327fad9bc.png)

**Comment by brianlmoon** [comment]
1. I would not run my workers as root.

2. If you run gearman manager without -d what is the console output?

**Comment by gzldx** [comment]
I will try it later. Thank you
