### ISSUE TITLE
Requiring A File??

### ISSUE THREAD

**Issue by NoiseEee** [brianlmoon/GearmanManager#116]
I'm finding that I cannot require or include a file, even though the path exists.

For example, I have a class called "test.php" in a specified gearman_workers dir, with the required "run" method.

From within that method, I cannot seem to include any found file (confirmed by "file_exists()") correctly. A require("../path/to/file.php") dies, and an include just doesn't work.

ie:

include.php = <?php  $f = "hi mom"; ?>

    public function run($job, $debug=false, &$log) {
      if(file_exists("../include.php")) {
          //i successfully enter this condition
          include("../include.php");
          return $f."!!!!";   //only returns "!!!!" instead of "hi mom!!!!";
       }
    }

I don't want to have to define database or other app variables/settings in each worker, i'd like them to pull that stuff in.  Is that not possible?

Thanks

**Comment by conradjones** [comment]
Yes it is possible I do it.

Is it a permission problem?

**Comment by NoiseEee** [comment]
I don't think so; file_exist() returns true so the file does exist, but anything I define that file is not accessible within my run() method.  Is it a scope issue / am I missing something obvious?

**Comment by conradjones** [comment]
I noticed yours in a parent folder. Try it in a subfolder of the workers.
Only php files in the "root" workers folder get auto-loaded by
Gearman-manager

**Comment by conradjones** [comment]
I'm presuming for the sake of this you are using PECL Version.

remove the @ from this line in GearmanPeclManager.php

60 - if(@$thisWorker->work() ||

and stop the gearman-manager service and run it from the command line
something like

gearman-manager -c /etc/gearman-manager/config.ini -vv

And you will probably see the error message causing it to die.

**Comment by NoiseEee** [comment]
@conradjones you sly dog, thank you so much!  indeed putting it in a subfolder within my workers folder worked properly.  THANK YOU!!!  Also, I'll use that last tip to debug further issues.

THANKS AGAIN!!

:hamburger:
