### ISSUE TITLE
Trying to get around typing "sudo service gearman-manager start" / autostarting

### ISSUE THREAD

**Issue by NoiseEee** [brianlmoon/GearmanManager#117]
Hi folks

I've done the ./install.sh script and indeed I can see I have a service called "gearman-manager" that I can issue start/stop commands to successfully, and then run jobs.

However, I have to start it explicitly / type "sudo service gearman-manager start" when my VM boots. What am I missing in order for the service to start automatically?

Debian Wheezy fwiw

Thanks!

**Comment by NoiseEee** [comment]
I will note that the traditional means, "sudo update-rc.d gearman-manager defaults" does not have any effect.

**Comment by conradjones** [comment]
i think you want update-rc.d gearman-manager enable

not defaults

**Comment by NoiseEee** [comment]
Hmm, still no go.  Not the end of the world, but frustrating :)

**Comment by conradjones** [comment]
i think the defaults is not working as I gearman-manager boots at startup
on of our webservers but doesn't work you have to start it and then stop it
again...............

but of course works fine on my development box.
