### ISSUE TITLE
weird @ problem

### ISSUE THREAD

**Issue by conradjones** [brianlmoon/GearmanManager#118]
I've got a worker that does (see below)

It fails at the $magento_model->save(); line.

So I'd thought I'd remove the @ from GearmanPeclManager.php line that says @thisworker->work() 

Then the worker executes fine and returns 0 instead of 255. But doesn't display any errors on the screen. I suspect this is some odd behaviour of the @ in php and the Zend Framework which magento uses but I can't figure out what? It's not the end of the world as I normally roll with the @ removed but it would be nice to figure what it is, otherwise we I either have to remember to patch gearman-manager or build something with salt-stack for it.

class MagentoProductSetRetailPrice extends GearmanWorkerBase
{
    public static function run_extended($instance)
    {
        $product_collection = Mage::getModel('dropshipproduct/dropshipproduct')
            ->getCollection()
            ->addFieldToFilter('sku', array("in" => $instance->skus));

```
    foreach ($product_collection as $product) {
        if ($magento_model = $product->getMagentoModel()) {

            $magento_model
                ->setPrice($product->calculatePrice());
            $magento_model
                ->save();
        }
    }
}
```

}

**Comment by brianlmoon** [comment]
I am guessing this is there because the PECL library throws a bunch of useless error messages that are already trapped by the code. I can see where it would hide error messages though from the calling code. I don't use the PECL bridge, so I am hesitant to just make that change blindly.
