### ISSUE TITLE
infinite max_worker_lifetime and max_worker_lifetime per each registered function

### ISSUE THREAD

**Issue by Dimonicus** [brianlmoon/GearmanManager#119]
There is a case when it is required to run workers:
1. Infinitely (new)
2. Limited amount of time (already implemented)

Is the option of running a worker infinitely possible? 

If yes:
Currently max_worker_lifetime is possible to define only as a general setting for all registered workers. In case when there are multiple workers and they have different lifetime limitation, some of them may not have the limit, it would be nice to have an option of defining the max_worker_lifetime per each registered function as well.

If no: 
An option to define max_worker_lifetime per each registered function would be great.

**Comment by brianlmoon** [comment]
What happens when a worker does multiple jobs with different max lifetimes? We could only allows this setting for dedicated workers. That would resolve the issue.
