### ISSUE TITLE
Does GearmanManager distribute jobs?

### ISSUE THREAD

**Issue by kobell** [brianlmoon/GearmanManager#120]
Hi,

I have a master server running gearman-manager (10.0.8.196) configured to connect to hosts 10.0.8.221 and 10.0.8.222, each running gearmand.

I start gearman-manager on host, it is successful, each node shows it is ready to receive jobs.

I execute a PHP script that sends a gearman job to 10.0.8.196, but it never gets passed to either child node.

Am I trying to do something that is not allowed?

**Comment by brianlmoon** [comment]
You should be running gearmand somewhere. And that is where you should send jobs.

**Comment by kobell** [comment]
Brian - thank you so much. I thought I had the model worked out in my head and just tried what you said. AMAZING!!! Thank you :)
