### ISSUE TITLE
start gearman manager with system start

### ISSUE THREAD

**Issue by bsn** [brianlmoon/GearmanManager#128]
please advice how to add starting gearman manager it to init.d or upstart, thanks!

**Comment by brianlmoon** [comment]
There are a few init scripts in the v1 branch that were contributed. I don't use them so was unable to port them to the new master. A pull request is welcome. 

https://github.com/brianlmoon/GearmanManager/tree/v1/install

**Comment by conradjones** [comment]
I just use supervisord as I use it for other bits too.

**Comment by brianlmoon** [comment]
Similarly, we use daemontools to run it which is started by init.
