### ISSUE TITLE
Gearman-manager processes take 100% CPU even with no jobs running

### ISSUE THREAD

**Issue by bartzy** [brianlmoon/GearmanManager#13]
Hi,

Running Gearman-manager (installing with install.sh, Debian squeeze 32-bit), with 1 job file with dedicated_count=4, the CPU utilization of the Gearman-manager processes is 100%.

No jobs are being sent through gearmand.

How can I debug this?

Thanks,
Bar.

**Comment by moein7tl** [comment]
same problem!

**Comment by brianlmoon** [comment]
Hmm, that strace is all stuff that happens in the PECL lib, GearmanManager does not handle the connections to the server. Are you using the most recent versions of the PECL lib and libgearman?

**Comment by conradjones** [comment]
Also what version of PHP are you running.

**Comment by dbaltas** [comment]
@brianlmoon which version of libgearman and pecl gearman are supported?
One idea might be to download libgearman 1.0.6 and pecl 1.1.1.
For ubuntu 12.04 the default libgearman is 0.x which has known issues.

**Comment by conradjones** [comment]
It works fine the unbuntu 14.04 and the latest version available in that.

**Comment by brianlmoon** [comment]
@dbaltas There is nothing in GearmanManager that requires any certain version of the PECL library. I personally use https://github.com/brianlmoon/net_gearman. So I don't dog food PECL unfortunately. I can test it, make sure it functions. But, for long running, high performance issues, I am relying on the community to fill in those gaps.
