### ISSUE TITLE
gearmand will stuck when client add multi server to request background job?

### ISSUE THREAD

**Issue by NewbMiao** [brianlmoon/GearmanManager#131]
it happens to me when use gearman with gearman-manger.

when a client (on php-fpm) add **multi server**,and request some **background job** ,
the first response jobserver(if already doing some background job) will **stuck till done previous job**. 
so it will make php-fpm timeout and never free resource(like mysql connection).

but if the client **only add one server** to  request some background job,server will never stuck.

why ?does something wrong ?pls give me some tips to solve it.

Dev:
gearmand-1.1.12
gearman-1.1.2
php-5.4
centos 6.5

---

it seems have problems  with gearman manager,does anyone use gearman manger in **multiserver** ?

**Comment by brianlmoon** [comment]
Can you provide sample code to reproduce? You say this is a GearmanManager problem, but talk about pho-fpm. Those are unrelated.
