### ISSUE TITLE
Errors with "pcntl_fork()" with PHP 7

### ISSUE THREAD

**Issue by NoiseEee** [brianlmoon/GearmanManager#136]
Hi there.... With PHP 7 and a pecl_gearman built for PHP 7 (via the great https://github.com/wcgallego/pecl-gearman )... If I have gearman manager waiting for some tasks for less than 24 hours, inevitably I get:

```
PHP Warning:  pcntl_fork(): Error 12 in /usr/local/share/gearman-manager/GearmanManager.php on line 929
PHP Stack trace:
PHP   1. {main}() /usr/local/share/gearman-manager/pecl-manager.php:0
PHP   2. GearmanManager->run($config = *uninitialized*) /usr/local/share/gearman-manager/pecl-manager.php:18
PHP   3. GearmanManager->process_loop() /usr/local/share/gearman-manager/GearmanManager.php:275
PHP   4. GearmanManager->start_worker($worker = *uninitialized*) /usr/local/share/gearman-manager/GearmanManager.php:316
PHP   5. pcntl_fork() /usr/local/share/gearman-manager/GearmanManager.php:929
```

And no gearman tasks will run again until i "sudo service gearman-manager (re)start"

I think I've had this error before on builds where the pecl lib of gearman doesn't match the installed libgearman lib, but I've been using PHP 5.6 and GearmanManager and official "pecl install gearman" wonderfully together in production over the past year or so.

I'd like to move to PHP7 but this is holding me back; ultimately I'm not sure what the issue is (ie: do I file an issue under that pecl-gearman fork as well?) but since the error I'm seeing is coming from Gearman Manager, I'm starting here. :)

**Comment by brianlmoon** [comment]
Error 12 indicates an out of memory error trying to fork. I have not tried GM with PHP 7 yet. Was this on the same machine where 5.x runs fine?

**Comment by brianlmoon** [comment]
I just read a thread on PHP Internals about segfaults before fork with PHP 7 due to some issues with memory allocation on Linux. It sounds exactly like this problem.

https://marc.info/?l=php-internals&m=145844820507918&w=2
