### ISSUE TITLE
How GearmanManager distributed tasks?

### ISSUE THREAD

**Issue by haihq88** [brianlmoon/GearmanManager#144]
Suppose i have 2 gearman servers with configure -h a.b.c.d:4730,A.B.C.D:4730.
How GearmanManager will distributes jobs to each gearman server?
@brianlmoon Can you help?
Thanks!

**Comment by clagiordano** [comment]
GearmanManager doesn't distribuite any jobs, only handle local machine functions (aka jobs or worker) and keep its running.
Gearman server distributes jobs between machines connected to it, indeed you cannot call directly the worker machine but call a specific gearman server for job, so you can try to connect any workers to two or more gearman server through gearman manager config file or CLI but I'm not sure about right config syntax.
