### ISSUE TITLE
Question about -vvv    Logs information about workers and the work they are doing

### ISSUE THREAD

**Issue by masterseo2000** [brianlmoon/GearmanManager#148]
Hello,
THis is more like a  question. I wanted to get some more details on this:
-vvv    Logs information about workers and the work they are doing
does it return the function being processed or the workload or both?
Thanks a lot! This looks like a wonderful tool 👍

**Comment by brianlmoon** [comment]
-vvv will tell you when a worker does a job. It does not tell you the inputs or outputs. There is no verbosity level which logs inputs and outputs. You would need to do that in your worker code.
