### ISSUE TITLE
Where is the v1 branch?

### ISSUE THREAD

**Issue by kevinc1984** [brianlmoon/GearmanManager#149]
Hi Brian,

My docker build just failed and I noticed the v1 branch had disappeared. Is there a commit SHA you'd recommend I try and clone and use? I should also probably just upgrade to v2, I'd just need to figure out what is so different.

Many Thanks!

**Comment by brianlmoon** [comment]
Packagist was complaining about the composer file in that branch. I have no plans to make any changes in the v1 branch. If you need to keep using v1 code, you could use the tag. https://github.com/brianlmoon/GearmanManager/releases/tag/v1.0.0
