### ISSUE TITLE
Support for includes and more in worker files

### ISSUE THREAD

**Issue by chaud** [brianlmoon/GearmanManager#15]
I have a current setup that utilizes some includes and helper functions in my workers, making it impossible to use GearmanManager. On startup: "INFO   Child exited with non-zero exit code 65280." 

It would be helpful if you could utilize require_once() and other functions instead of only being able to have one function in the worker file. Maybe being able to define a worker in the normal way, allowing drop in support or minimal modification for current Gearman worker setups.

**Comment by shiqiliang** [comment]
The error also happens to me too, Seems it works fine if I use the absolute path.

**Comment by conradjones** [comment]
I have this at the top of all my workers

require "lib/autoload.php";
require_once 'include/paths.php';

works fine.
