### ISSUE TITLE
Missing composer check for Gearman Extension

### ISSUE THREAD

**Issue by ReduktorSpalin** [brianlmoon/GearmanManager#155]
I think this project should have more verbose dependency on `ext-gearman` in `composer.json`.
It misses line: `"ext-gearman":"*"`.

This way, if gearman extension was not installed by chance it can be early detected with composer's `check-platform-reqs` command.

**Comment by brianlmoon** [comment]
ext-gearman is not required.

**Comment by ReduktorSpalin** [comment]
Maybe that is incorrect solution. But problem is still there (I think).
IMHO if Any of required classes in `GearmanPearManager` would be missing, script should exit with some error message and code to help target issue, instead of silently requiring dependencies.

I might be wrong, but I feel it might get confusing. Maybe there should be separate function : check lib dependencies (with default implementation) and overriden by each of adapters (Pecl and Pear).

That's just my guess.

**Comment by brianlmoon** [comment]
What would happen if you didn’t have either the pecl or pear lib installed? It would not be silent. And the README clearly states the requirements. In the seven years this project has been in use, this has never been an issue.
