### ISSUE TITLE
Helper child exited with non-zero exit code 65280

### ISSUE THREAD

**Issue by dl-lewis** [brianlmoon/GearmanManager#156]
So, I am using includes in my worker files, but am using absolute paths. I am unable to see any errors even when using xdebug's scream. Nothing is logged in the manager log; no errors are logged in the normal error.log.

When I run pecl-manager.php, this is the output I get:

25167 DEBUG  Registering signals for parent
25167 INFO   Loading workers in /path/to/workers
25167 PROC   Helper forked with pid 25168
25168 INFO   Loading workers in /path/to/workers/workers
25167 INFO   Helper child exited with non-zero exit code 65280.

**Comment by brianlmoon** [comment]
Are you using Windows? This is all I can find on that exit code. http://wiki-errors.com/err.php?wiki=65280

**Comment by dl-lewis** [comment]
No, Ubuntu 18.04

**Comment by dl-lewis** [comment]
We figured out this was because of relative paths in other files included in our includes. Thank you for responding, though, and for this package!
