### ISSUE TITLE
Support log rotation

### ISSUE THREAD

**Issue by sgtsquiggs** [brianlmoon/GearmanManager#95]
I'm trying to rotate the logs for GearmanManager, but as expected it continues to write to the original log. I am rotating with newsyslog on freebsd. Does GearmanManager expect a signal?

Thanks

**Comment by brianlmoon** [comment]
This was added in the overhaul. https://github.com/brianlmoon/GearmanManager/blob/master/src/GearmanManager/GearmanManager.php#L1042
